Bugfix/wifi
SymetriaSpJ/phonegap-plugin-cordova-plugin-network-information pull request #1
Opened 2016-12-06 09:44 UTC by gczudowski

### Platforms affected

### What does this PR do?

### What testing has been done on this change?

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

2016-12-06 09:50 UTC, robertgacki requested changes

2016-12-06 09:50 UTC, robertgacki commented on www/network.js
> +var timeout = 500;
to 500 ma jakąś przyczynę?

2016-12-06 10:01 UTC, gczudowski commented on www/network.js
> +var timeout = 500;
jest to kod z oryginalnej linii 53 (wyżej). opóźnia wysłanie informacji o statusie offline do apki.

2016-12-06 13:22 UTC, gczudowski commented on www/network.js
> +var timeout = 500;
zostaje

2016-12-06 14:32 UTC, xkxd approved these changes

2016-12-07 06:01 UTC, robertgacki approved these changes

2016-12-08 10:00 UTC, astanecki requested changes

2016-12-08 10:00 UTC, astanecki commented on www/network.js
> +NetworkConnection.prototype.getInfo = function() {
jak już edytujemy to proponuję pokusić się o zmianę nazwy, np. checkCurrentStatus. W appce wołana metoda wygląda jakby gdzieś miała coś zwracać

2016-12-08 10:00 UTC, astanecki commented on www/network.js
> +    me.getInfo();
tu właściwie anonimowa metoda nie jest potrzebna

2016-12-08 10:00 UTC, astanecki commented on www/network.js
> +channel.waitForInitialization('onCordovaConnectionReady');
to się nie chainuje tak?

2016-12-08 14:02 UTC, dahel requested changes

2016-12-08 14:02 UTC, dahel commented on www/network.js
> +NetworkConnection.prototype.getInfo = function() {
spacja po function

2016-12-08 14:02 UTC, dahel commented on www/network.js
> +NetworkConnection.prototype.getInfo = function() {
Proponuje nie zmieniać nazw stworzonych przez autora pluginu, trzeba by potem dokumentacje przepisać.. 🌺

2016-12-13 10:50 UTC, gczudowski commented on www/network.js
> +channel.waitForInitialization('onCordovaConnectionReady');
to się nie chainuje

2016-12-13 10:50 UTC, gczudowski commented on www/network.js
> +NetworkConnection.prototype.getInfo = function() {
ok

2016-12-13 13:15 UTC, astanecki approved these changes

2016-12-14 08:50 UTC, dahel approved these changes

2016-12-14 08:55 UTC, merged